# Generated by Django 3.1.3 on 2021-05-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_company', models.CharField(max_length=250)),
                ('job_desc', models.TextField()),
                ('start_date', models.DateField(verbose_name='Date Hired')),
            ],
        ),
    ]
